# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la oportunidad')),
                ('stage', models.CharField(choices=[('prospecting', 'Prospección'), ('qualification', 'Cualificación'), ('proposal', 'Propuesta'), ('negotiation', 'Negociación'), ('closed_won', 'Cerrada - Ganada'), ('closed_lost', 'Cerrada - Perdida')], default='prospecting', max_length=20, verbose_name='Etapa')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor (€)')),
                ('probability', models.IntegerField(default=0, verbose_name='Probabilidad (%)')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de cierre')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre real')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('loss_reason', models.TextField(blank=True, verbose_name='Motivo de pérdida')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='contacts.company', verbose_name='Empresa')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='contacts.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
            },
        ),
    ]
