# Generated by Django 4.2.29 on 2026-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='competitor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Competidor'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='loss_reason_category',
            field=models.CharField(blank=True, choices=[('price', 'Precio'), ('competitor', 'Competencia'), ('no_budget', 'Sin presupuesto'), ('timing', 'Mal momento'), ('no_fit', 'No encaja el servicio'), ('internal_decision', 'Decisión interna cambió'), ('no_response', 'Dejó de responder'), ('other', 'Otro')], max_length=20, verbose_name='Categoría de pérdida'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='next_step',
            field=models.CharField(blank=True, max_length=255, verbose_name='Próxima acción'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cambio de etapa'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='win_reason',
            field=models.CharField(blank=True, choices=[('price', 'Precio competitivo'), ('trust', 'Confianza / relación'), ('service_fit', 'Servicio a medida'), ('referral', 'Recomendación'), ('speed', 'Velocidad de respuesta'), ('expertise', 'Conocimiento / expertise'), ('other', 'Otro')], max_length=20, verbose_name='Motivo de cierre ganado'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='loss_reason',
            field=models.TextField(blank=True, verbose_name='Detalle del motivo de pérdida'),
        ),
    ]
