# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('social', 'Redes Sociales'), ('event', 'Evento'), ('advertising', 'Publicidad'), ('referral', 'Referencia'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto (€)')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coste real (€)')),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingreso esperado (€)')),
                ('target_audience', models.TextField(blank=True, verbose_name='Público objetivo')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('opened', 'Abierto'), ('clicked', 'Click'), ('responded', 'Respondido'), ('converted', 'Convertido'), ('bounced', 'Rebotado')], default='sent', max_length=20, verbose_name='Estado')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío')),
                ('opened_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha apertura')),
                ('clicked_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha click')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campaigns.campaign', verbose_name='Campaña')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='contacts.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Miembro de campaña',
                'verbose_name_plural': 'Miembros de campaña',
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
