# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Tecnología'), ('finance', 'Finanzas'), ('healthcare', 'Salud'), ('education', 'Educación'), ('retail', 'Comercio'), ('manufacturing', 'Manufactura'), ('services', 'Servicios'), ('energy', 'Energía'), ('real_estate', 'Inmobiliario'), ('other', 'Otro')], max_length=50, verbose_name='Sector')),
                ('size', models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501-1000', '501-1000 empleados'), ('1000+', 'Más de 1000 empleados')], max_length=20, verbose_name='Tamaño')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email corporativo')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Facturación anual')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Móvil')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('prospect', 'Prospecto'), ('customer', 'Cliente'), ('churned', 'Perdido')], default='prospect', max_length=20, verbose_name='Estado')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('description', models.TextField(blank=True, verbose_name='Notas')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contact_avatars/', verbose_name='Foto')),
                ('do_not_call', models.BooleanField(default=False, verbose_name='No llamar')),
                ('do_not_email', models.BooleanField(default=False, verbose_name='No enviar emails')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'unique_together': {('email', 'company')},
            },
        ),
    ]
