# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('service', models.CharField(choices=[('calendar', 'Calendario'), ('contacts', 'Contactos'), ('phone', 'Teléfono'), ('files', 'Archivos'), ('email', 'Mail')], max_length=20, verbose_name='Servicio')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('partial', 'Parcial')], max_length=10, verbose_name='Estado')),
                ('records_synced', models.PositiveIntegerField(default=0, verbose_name='Registros sincronizados')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Log de sincronización',
                'verbose_name_plural': 'Logs de sincronización',
            },
        ),
    ]
