# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Empresa')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('website', models.URLField(blank=True, verbose_name='Web')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Cualificado'), ('unqualified', 'No cualificado'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(blank=True, choices=[('website', 'Sitio web'), ('referral', 'Referencia'), ('social_media', 'Redes sociales'), ('email_campaign', 'Campaña de email'), ('cold_call', 'Llamada en frío'), ('event', 'Evento'), ('advertising', 'Publicidad'), ('partner', 'Partner'), ('other', 'Otro')], max_length=20, verbose_name='Origen')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('score', models.IntegerField(default=0, verbose_name='Puntuación (0-100)')),
                ('score_reasons', models.JSONField(blank=True, default=list, verbose_name='Razones del scoring')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('converted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conversión')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campaigns.campaign', verbose_name='Campaña')),
                ('converted_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_lead', to='contacts.contact', verbose_name='Contacto convertido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
