# Generated by Django 4.2.29 on 2026-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='disqualification_reason',
            field=models.CharField(blank=True, choices=[('no_budget', 'Sin presupuesto'), ('no_authority', 'No es el decisor'), ('no_need', 'No tiene la necesidad'), ('bad_timing', 'Mal momento'), ('competitor', 'Fue con la competencia'), ('no_response', 'Sin respuesta'), ('other', 'Otro')], max_length=20, verbose_name='Motivo de descarte'),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de seguimientos'),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_budget',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tiene presupuesto?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('cold', 'Frío'), ('warm', 'Tibio'), ('hot', 'Caliente')], max_length=10, verbose_name='Nivel de interés'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_decision_maker',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es el decisor?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contacto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo seguimiento'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pain_point',
            field=models.TextField(blank=True, verbose_name='Problema / necesidad'),
        ),
    ]
