# Generated by Django 4.2.29 on 2026-03-28 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('trigger', models.CharField(choices=[('lead_created', 'Nuevo lead creado'), ('lead_status_changed', 'Lead cambia de estado'), ('opportunity_created', 'Nueva oportunidad creada'), ('opportunity_stage_changed', 'Oportunidad cambia de etapa'), ('contact_created', 'Nuevo contacto creado'), ('activity_completed', 'Actividad completada'), ('ticket_created', 'Nuevo ticket creado'), ('scheduled', 'Programado (cron)')], max_length=30, verbose_name='Disparador')),
                ('action', models.CharField(choices=[('send_email', 'Enviar email'), ('create_activity', 'Crear actividad'), ('assign_user', 'Asignar usuario'), ('update_field', 'Actualizar campo'), ('create_notification', 'Crear notificación')], max_length=30, verbose_name='Acción')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de acción')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Condiciones')),
                ('execution_count', models.PositiveIntegerField(default=0, verbose_name='Veces ejecutado')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True)),
                ('affected_object_id', models.CharField(blank=True, max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflow')),
            ],
            options={
                'verbose_name': 'Log de workflow',
                'verbose_name_plural': 'Logs de workflows',
                'ordering': ['-executed_at'],
            },
        ),
    ]
