# Generated by Django 4.2.29 on 2026-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, verbose_name='Próxima acción'),
        ),
        migrations.AddField(
            model_name='activity',
            name='next_action_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha próxima acción'),
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('no_answer', 'No contestó'), ('callback_scheduled', 'Llamada agendada'), ('interested', 'Interesado'), ('not_interested', 'No interesado'), ('send_info', 'Pidió información'), ('meeting_scheduled', 'Reunión agendada'), ('proposal_requested', 'Pidió propuesta'), ('other', 'Otro')], max_length=20, verbose_name='Resultado'),
        ),
    ]
